DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE TABLE users
(
    id    bigint generated by default as identity primary key,
    name  varchar not null,
    email varchar not null unique
);

CREATE TABLE items
(
    id          bigint generated by default as identity primary key,
    user_id     bigint,
    name        varchar not null,
    description varchar not null,
    available   boolean not null,
    foreign key (user_id) references users (id)
);

CREATE TABLE bookings
(
    id            bigint generated by default as identity primary key,
    user_id       bigint,
    item_id       bigint,
    start_booking timestamp not null,
    end_booking   timestamp not null,
    status        varchar   not null,
    foreign key (user_id) references users (id),
    foreign key (item_id) references items (id)
);

CREATE TABLE comments
(
    id      bigint generated by default as identity primary key,
    user_id bigint,
    item_id bigint,
    created timestamp not null,
    text    varchar   not null,
    foreign key (user_id) references users (id),
    foreign key (item_id) references items (id)
);